"""baseline schema

Revision ID: 16a3d158f775
Revises: 
Create Date: 2026-07-12 01:39:43.386679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a3d158f775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_cn', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('medical_information', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('registration_group', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('state_region', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('helper_count', sa.Integer(), nullable=True),
    sa.Column('helper_names', sa.Text(), nullable=True),
    sa.Column('special_request', sa.Text(), nullable=True),
    sa.Column('accommodation_required', sa.Boolean(), nullable=True),
    sa.Column('roommate_name', sa.String(length=100), nullable=True),
    sa.Column('roommate_doc_no', sa.String(length=50), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('payment_currency', sa.String(length=10), nullable=True),
    sa.Column('participant_category', sa.String(length=50), nullable=True),
    sa.Column('original_payment_amount', sa.Float(), nullable=True),
    sa.Column('original_payment_currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('exchange_rate_date', sa.String(length=20), nullable=True),
    sa.Column('paper_presentation', sa.Boolean(), nullable=True),
    sa.Column('paper_files', sa.Text(), nullable=True),
    sa.Column('payment_doc', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=True),
    sa.Column('student_card_no', sa.String(length=100), nullable=True),
    sa.Column('student_card_expiry', sa.String(length=20), nullable=True),
    sa.Column('student_school', sa.String(length=200), nullable=True),
    sa.Column('student_card_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('paper_title', sa.String(length=300), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('validfy', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.String(length=100), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['register_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_transaction')
    op.drop_table('register_data')
    # ### end Alembic commands ###
